### ISSUE TITLE
Plugin adds classes to select element

### ISSUE THREAD

**Issue by StijnCoolen** [barrelstrength/craft-sprout-forms#174]
### Description
Plugin adds a `class` based on the field handle  to `select` elements.
Even when the _CSS Classes_ field has been left empty.

### Steps to reproduce

1. Create a form and add a form field
2. Add a handle to this field
3. See class of `select` element

### Additional info

- Craft version: Craft Solo 3.0.26.1
- PHP version: 7.1.22
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Sprout Forms 3.0.0-beta.26

**Comment by BenParizek** [comment]
@StijnCoolen This is expected behavior. We add several IDs and classes based on the form and field information to give folks who are using the default templates options if they want to style or interact with the default form and field templates. If you do add custom classes, by default, we add them to the field wrapper divs, so that you can target anything within the field div that you'd like.

If you have a situation that requires different behavior or you'd just prefer to control your templates and classes in a different way, we also give you full control over the templates you are using Template Overrides: https://sprout.barrelstrengthdesign.com/docs/forms/template-overrides.html

In the global Sprout Forms settings, or on a per-form basis, you can define a custom Form Template folder in your Craft templates folder and adjust the default form however you'd like there. You can find the default Form Templates here if you'd like to copy them as a starting point: https://github.com/barrelstrength/craft-sprout-forms/tree/v3/src/templates/_components/formtemplates/accessible
