### ISSUE TITLE
Get user input in notification e-mail template

### ISSUE THREAD

**Issue by johnvanhulsen** [barrelstrength/craft-sprout-forms#218]
### Description
Is it possible to get the user given input on the form back into the e-mail notification template?
In beta 26 the following is possible:
```
{% set tab = object.getFieldLayout().getTabs()[0] %}
{% set fields = tab.getFields() %}
```

I've running beta 35 now, and then I get an error on it:
```
Argument 1 passed to barrelstrength\sproutforms\services\Forms::getFormById() must be of the type integer, null given, called in /vagrant/team-jumbo/vendor/barrelstrength/sprout-forms/src/elements/Entry.php on line 420
```
Is the way of use changed? In addition, does not this seem to me the most convenient way. Are there docs how to use this?

### Additional info

- Craft version: 3.0.36
- PHP version: 7.2.13
- Plugins & versions: 3.0.0-beta.35

**Comment by johnvanhulsen** [comment]
Thnx for the answer @BenParizek. The {{object.entry}} option looks great with the example.
But there is one problem. Also on {{object.entry}} I've get the getFormById() error that I described above.

But, no I've never use getFormById().
The steps:
- I made a form, add it to an entry and submit it;
- in the e-mail template there is nothing inside by now, except `{{dump(object.entry}}`;
- I receive an e-mail with the title of the notification. Body is empty.

For debugging i use the e-mail preview (right anchor on the notification overview). I assume that this should not be a problem?
In that preview I've got the error from above.

**Comment by BenParizek** [comment]
Thanks for the additional details @johnvanhulsen 

I'll need to get this in our queue to look into a bit more but, in the meantime, you may want to trigger an actual test email. The bug you are running into may just have to do with the Email Preview behavior you are using. That preview functionality relies on us generating a mock object that represents the form that is being submitted (because no form has actually been submitted). So when you click that preview button it is looking at your "When a form is saved" Notification Event settings and possibly not finding the Form ID that you have selected. Or possibly you have "All forms" selected and our code gets confused and doesn't know which form to use for the example. 

I'm not sure what the issue is but we can take a look into it. Let me know if the workaround of submitting an actual form to test the notification doesn't work too.

**Comment by pdaleramirez** [comment]
I tested this again and we can still passed in object variable to the email template. I was not able to reproduced the issue but i think the problem is that you are triggering the notification event on a form that has been since deleted. @johnvanhulsen @BenParizek

**Comment by BenParizek** [comment]
@johnvanhulsen As we haven't heard back from you on this and haven't been able to recreate, I'm going to close this out for now. If it continues, and you can provide more info to help us track it down, feel free to reopen the conversation.
