### ISSUE TITLE
Column not found: 1054 Unknown column 'pluginHandle' in 'field list'

### ISSUE THREAD

**Issue by stromjoe** [barrelstrength/craft-sprout-forms#286]
### Description
Customer reporting not being able to enter "Reports" section to export their Sprout Forms data, instead the following error appears:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pluginHandle' in 'field list'
The SQL being executed was: SELECT DISTINCT `pluginHandle`
FROM `craft_sproutreports_datasources`

I tried updating plugins and Craft CMS on my local environment (version information under "Additional info") without success. Any help would be greatly appreciated!

### Additional info

- Craft version: Local Craft Pro 3.2.0-beta.1 / Production Craft Pro 3.1.19
- PHP version: Local 7.2 / Production 7.3.3
- Database driver & version: Local MySQL 5.6.42 / Production MySQL 5.7.25 
- Plugins & versions: Local 3.0.0-beta.57 / Production 3.0.0-beta.49

**Comment by BenParizek** [comment]
Hi @stromjoe.

It sounds like a migration was missed that adds that column to the database. The migration appears to have been added in Sprout Forms v3.0.0-beta.51 so that should solve your issue on production and the question becomes why that migration never got run when you upgraded things in your local environment. 

Can you explain in more detail what steps you took to upgrade the plugin locally? Perhaps that will help us track down where to look next.

For your reference, here's a link to a response I recently wrote to an (unrelated) question that describes how to make sure you're getting everything updated to the latest with composer:
https://craftcms.stackexchange.com/a/30535/115

**Comment by stromjoe** [comment]
Hello

I duplicated my production environment over to staging to see if an update to Sprout Forms v3.0.0-beta.51 would fix the issue, but I'm still getting the same error when trying to access the Reports section.

On my local I took the steps you described in the link and updated everything at the same time to the newest versions with composer update but that didn't have any impact either and the issue remains.

I know that this site originally got upgraded from Craft 2 to Craft 3, so there must have been some misstep along the process which created this issue. Checking with the team if they have any ideas about this and will post back if we find a solution.

**Comment by BenParizek** [comment]
@stromjoe Ok. If you can't roll back and re-run the migrations, the best path forward may be to install a fresh copy of Sprout Forms in a dev environment and then compare the database tables in your current setup to the fresh install. The error indicates that at least one column is missing in the current setup (`sproutreports_datasources.pluginHandle`).

If you're not comfortable with that, feel free to drop me a note via email sprout@barrelstrengthdesign.com or on Craft Discord (BenParizek) and we can find a time to connect and review via screen share and get things sorted out.

**Comment by stromjoe** [comment]
Hello

I compared the database columns and noticed that `sproutreports_datasources.pluginHandle` was indeed missing. I went ahead and added it in:

![Screenshot 2019-06-27 at 16 03 39](https://user-images.githubusercontent.com/9196774/60268541-485d6300-98f5-11e9-9399-f546f2613f69.png)

At first everything seemed to work again, I was able to access the Reports section. However, when I created a new report and saved it, I didn't see it anywhere on the list:

![Screenshot 2019-06-27 at 15 58 46](https://user-images.githubusercontent.com/9196774/60268601-6d51d600-98f5-11e9-848f-0f6056f2ca75.png)
![Screenshot 2019-06-27 at 15 58 53](https://user-images.githubusercontent.com/9196774/60268606-72168a00-98f5-11e9-8c18-3e44e26704e1.png)

I then tried to update the plugin to the newest version, but that seemed to have made it worse because now I can't see the red "New report" button anymore above the reports listing.

Any suggestions on which steps I should take next? I could provide you with logs in case that would be of help.

**Comment by BenParizek** [comment]
@stromjoe I'm looking into this more think this may be a new bug.

Can you take a look at the `sproutreports_datasources.pluginHandle` column. I think we may have a bug that sets that to `sprout-reports` for Sprout Forms reports. If you see that, you should be able to update the value for the Sprout Forms Report option to `sprout-forms` and see that New Report button again.

**Comment by stromjoe** [comment]
It was empty for me, so I went ahead and added sprout-forms to it.

![Screenshot 2019-06-28 at 11 24 48](https://user-images.githubusercontent.com/9196774/60328670-6da2ad80-9997-11e9-868b-102926c64619.png)
 
After the change I could see the "New Report" button again, but the reports list was still empty. This was weird because the craft_sproutreports_reports had old reports stored in it. Also, when trying to create new reports they didn't appear at all in the craft_sproutreports_reports table. 

I updated the plugin to the newest version again which fixed the issue of not seeing the reports in the list view, and they are now being added correctly to the database. However, now I'm only able to create a report from one form, and for some reason I can only see that one form in the form list as well, even though it says that there are 17 elements. 

![Screenshot 2019-06-28 at 11 34 54](https://user-images.githubusercontent.com/9196774/60329416-fc63fa00-9998-11e9-8fdf-91e2c077a563.png)

Any idea what could be the reason for this? Thanks for your help so far!

**Comment by BenParizek** [comment]
Hi @stromjoe. Thanks for your patience. The issue of only seeing one form is due to the latest release where we added support for Editions. There is now a Lite Edition (which restricts usage to one form) and a Pro Edition (which I assume you have a license for). 

We have had other reports of users updating to the latest version and the Edition not getting set properly by Craft during the update. One user had to manually add `edition: pro` to their Project Config `project.yaml` file.

Can you find the Sprout Forms plugin in the Plugin Store and select the "Try" option for the Pro version? This should get Craft to add that line for you and, if you already have a license, I would guess that helps get things resolved and displaying again.

I'll reach out to Craft support to see if we can figure out what's going on here and correct this bug in the future.

**Comment by BenParizek** [comment]
@stromjoe The latest release of Sprout Forms(v3.2.2) adds a migration to address both of these scenarios (ensuring your edition is set to `pro` when updating and ensuring that the right values are stored in the reports table).

As this thread has taken a few different directions, I'm going to close it out but please open a new ticket if you continue to run into anything else.

**Comment by besimhu** [comment]
Wanted to leave a reply and say that I ran into this same error running 3.3.7 when upgrading from v2 to v3 of Sprout. Once I downgraded to 3.3.4 it worked again. 

I had a running v3 version of my site, but was getting the latest data from live for a final upgrade push and that is when I ran into the error.
