### ISSUE TITLE
Updating: Setting unknown property

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#296]
I just tried to update Sprout Forms from 43.0.0.-beta.57 to 3.1.0, and updated Craft at the same time from 3.1.27 to 3.1.31 and got this error message:

![image](https://user-images.githubusercontent.com/1250017/59840600-56dad600-935b-11e9-9a22-bf0083b56f5a.png)

After rolling back, I tried updating Craft first from 3.1.27 to 3.1.31, leaving Sprout Forms on the beta version. I got the same error message again.

I then updated Sprout Forms to 3.1.0, leaving Craft on 3.1.27 and it worked fine.

Then I continued to work through 3.1.28, 3.1.29, 3.1.30 and finally 3.1.31 to try and fin the problem and it STILL worked... so I have no idea what causes that problem as it's now all up to date. I guess this is just a heads up?

**Comment by BenParizek** [comment]
Thanks for the heads up @darylknight. I've scanned the code and don't see any obvious issues so I'll note this down if any related tickets come up.

I find that after some upgrades I run into similar errors and often the source of the issue is just the way Craft is caching files in the CP. It could be that after you upgraded Craft was just trying to do something with a cached file after the underlying data structured changed, and after you/Craft refreshed that cache, the requests were using the latest files and worked fine.

I'm not sure that was what was going on here, but if you run into something like this again it may be worth clearing cache in the Utilities tab on Craft and trying to reload the page again. If you or anybody run into this again, we'll dig deeper.

**Comment by darylknight** [comment]
Thanks Ben. FYI this might be related to Yii Framework notice below as I ran into this same issue on another site this morning.

![image](https://user-images.githubusercontent.com/1250017/60005876-083d7c80-9678-11e9-920e-2b518f8d27cf.png)
