### ISSUE TITLE
This license has expired

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#301]
### Description (screenshots, logs, ...)

I couldn't get Sprout Forms 3.0.0-beta.57 to update properly as it kept failing - it needed something like Sprout Base 5.0.4+ and wouldn't install it itself. I eventually gave up and nuked my /vendor folder and reinstalled everything from scratch. I've now installed 3.2.0 and I'm seeing this in the Plugin list:

![image](https://user-images.githubusercontent.com/1250017/60102762-fe467700-9766-11e9-83ff-ab5a3f9f8703.png)

This is what the Craft ID site says for that license:

![image](https://user-images.githubusercontent.com/1250017/60102940-58dfd300-9767-11e9-90f5-422527afc03c.png)

![image](https://user-images.githubusercontent.com/1250017/60102777-069eb200-9767-11e9-83ec-1297192a9b2a.png)

Craft 3.1.31

**Comment by BenParizek** [comment]
@darylknight Regarding the license, we did recently add a Lite and Pro edition of Sprout Forms, so perhaps this has to do with how legacy licenses are recognized. If you're using the project.yaml, you can try to update the edition to `pro`. Previously, when we only had one version I believe Craft identified it as `standard` so it's possible that somewhere in your settings (Project Config file or in the db) Craft is still referring to that `standard` version and needs to get updated to `pro` to recognize your license. If that doesn't resolve things, you'll probably need to reach out to Craft support. 

I'll follow up with them myself to learn what the expected behavior is for this scenario and post an update here with what I learn.

----

Regarding the upgrade, if you have multiple Sprout plugins installed on the site, sometimes they depend on different versions of some supporting modules. In these cases, you'll need to use the "Upgrade All" option within Craft to get everything updated at once (if you are upgrading from the CP), or, if you still run into issues, you've taken the right approach by deleting the vendor folder and re-running Composer to sort out all the dependency issues.

**Comment by brandonkelly** [comment]
Hey @darylknight can you please email support@craftcms.com, referencing this GH issue, and attach your `composer.json` file and a database backup?

**Comment by darylknight** [comment]
Thanks for the replies! Yes, I've emailed those.

**Comment by BenParizek** [comment]
@darylknight We've added a new migration in the latest version of Sprout Forms that should ensure your licensed version of Sprout Forms get updated to the `pro` edition when updating. Let me know if you run into anything else.
