### ISSUE TITLE
Documentation on form options / id not working as described

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#317]
The [docs](https://sprout.barrelstrengthdesign.com/docs/forms/rendering-options.html#overriding-values-via-the-displayform-tag) say you can change the ID of a field like this:

    {% set options = {
        "fields": {
            "fieldHandle": {
                "id": "myfield",
            }
        }
    %}

If you do this, the ID of the field is set to `fields-myfield` instead of the expected `myfield`

**Comment by BenParizek** [comment]
@darylknight The prefixing of the ID is expected behavior. It is happening because of the `namespace` tag in the underlying form template code in the `field.html` file and helps with ensuring things a few things are namespaced consistently including the `name` parameters on the inputs and the `id` attributes. 

https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/templates/_components/formtemplates/accessible/field.twig#L14

If you don't wish for this behavior, you can use template overrides to update how that works, you'll just have to be sure that you are naming your input fields in the appropriate way on your own to ensure your data can be submitted to wherever you are submitting it to (Craft or somewhere else via an Integration).

Classes do not get namespaced within the field template if you need something to be the specific name you are giving it.

**Comment by darylknight** [comment]
Thanks for the info Ben. While I totally understand the reasoning, the tpoic is still valid - the docs should be updated to say something like "The ID you specify will be prefixed with 'field-' "

**Comment by BenParizek** [comment]
@darylknight I'll reopen and update the docs to clarify when I have a chance.

The _Rendered HTML_ example in the docs does illustrate the prefix, but I think your right that most folks won't assume that is happening and it's worth calling out.

**Comment by BenParizek** [comment]
A note has been added to the docs on this behavior.
