### ISSUE TITLE
Required attribute missing from checkbox field and opt-in field

### ISSUE THREAD

**Issue by TomDeSmet** [barrelstrength/craft-sprout-forms#336]
### Description (screenshots, logs, ...)
When required is set in the CP on a checkbox field, the required attribute is not added to the field in the code. However, the form does not get saved to the DB but no error is triggered.

### Solution:
Add same code from single line field template to the checkbox field template:

`{%- set required = field.required ? true : false %}`
and
`{%- if required %} required aria-required="true"{% endif %}`

### Update:
Maybe also add a * to the label by default when a field is required?

**Comment by BenParizek** [comment]
@TomDeSmet In looking into this I recall why we currently don't support this. I don't believe HTML5 has a way to require a single checkbox in a group of checkboxes. While we could potentially add a required attribute if the list of checkboxes is only a single checkbox, adding a required attribute to all checkbox fields defeats the purpose of letting users choose a subset of options.

There appear to be some javascript workarounds to this, so I'll explore what those could look like and see if we can add support that way.

In your solution above, are you only outputting a single checkbox?

---

Regarding your comment "the form does not get saved to the DB but no error is triggered" I have not been able to recreate this. If the checkbox field is required, in my tests the form fails validation and presents an error. So I'll need more details if that is still an issue.

----

As for adding a star to required fields, we've chosen not to add too many options to the default templates as designers may want to style them using :after pseudo elements in CSS too. In most cases, I expect users will need to customize things via CSS or template overrides and we felt the default use case of leaving the templates as is and just styling them in CSS was a better default vs. requiring anybody that wanted to style them only with CSS to have to override the templates just to remove an asterix. In either case, we may in the future consider providing some additional default style options out of the box. I'll note this down for consideration as we explore those options.

**Comment by TomDeSmet** [comment]
Yes I am. It's a 'agree to our privacy policy' checkbox.

**Comment by BenParizek** [comment]
@tomdavies Two things here:

If you just need a single checkbox, the Opt-in Field is designed to be targeted at those types of use cases like Privacy Policy checkboxes and such. It's got a slightly different HTML output too that doesn't add the label above the field, but you can customize it like all the other fields how you wish as well. Just noting it as an option here.

To your original question, we've updated the default javascript included with the Accessible Form Templates to support required checkboxes. This needs to be done with javascript due to how checkbox inputs behave with the required tag so if you are using custom templates you may need to pull in or be inspired by how that is handled in the accessibility.js file.

Example of how to include the JS here:
https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/templates/_components/formtemplates/accessible/form.twig#L72

The JS file for reference: 
https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/web/assets/formtemplates/src/js/accessibility.js

**Comment by tomdavies** [comment]
@BenParizek think you meant to tag @TomDeSmet
