### ISSUE TITLE
Incorrect label for Postcode, 3.6.5 Lite

### ISSUE THREAD

**Issue by nyehughes** [barrelstrength/craft-sprout-forms#382]
When using the Address form field with countries that have a postcode field, it is incorrectly labeled as "Postal", it should be be "Postcode":

<img width="958" alt="Screenshot 2019-12-05 at 12 58 01" src="https://user-images.githubusercontent.com/3296602/70238742-cdc92700-1761-11ea-8ae2-332ea5ec358a.png">

**Comment by BenParizek** [comment]
@nyehughes We're pulling those labels in dynamically from a Google dataset. Here's a similar issue from the library we're using for more context: https://github.com/commerceguys/addressing/issues/111

While I can't update that label specifically, it does look like a newer version of the addressing library is out so I will make a note to get updated to the latest in case they address this.

**Comment by BenParizek** [comment]
https://github.com/barrelstrength/craft-sprout-fields/issues/97

**Comment by thisisjamessmith** [comment]
I'd like to add to this issue, that "Post town" is a bit weird - most people would like the option of specifying simply "Town" or "City" or some combination like "Town/City". What's the advantage of pulling all this address data dynamically from commerceguys instead of generating it in Sprout?

**Comment by BenParizek** [comment]
@thisisjamessmith We use the addressing library because there is no way we could curate or maintain the address specification and varying formats and changes over time on our own for over 200 countries.

You can read more about what Addressing provides in their [README](https://github.com/commerceguys/addressing) which also links to the Google Data set they use to generate Address formats and subdivisions.

I think your solution is a good workaround if you have a preference for those labels being different as we rely on whatever the addressing library provides us there. Outside of that, you would need to reach out to the folks who manage the respective data set to ask them why they've chosen these particular defaults. I'm no expert on addresses or how they make their choices around which labels they use but I would assume that it's not an arbitrary decision. I see the term [Post Town](https://en.wikipedia.org/wiki/Post_town) even has a Wikipedia page that states it is _a required part of all postal addresses in the United Kingdom and Ireland_.

**Comment by BenParizek** [comment]
The latest release v3.6.8 updates to the latest addressing library. The same terminology is used.

As this item is outside of our control, I'm going to close this out. See [this post above](https://github.com/barrelstrength/craft-sprout-forms/issues/382#issuecomment-571108358) for a workaround if you have a preference on the address output language. Aside from that, you'll need to make this request directly to Google or whoever manages the data set that we're using which you can find discussed in the [addressing readme](https://github.com/commerceguys/addressing)
