### ISSUE TITLE
Notification email sent when reCaptcha has not been completed

### ISSUE THREAD

**Issue by javangriff** [barrelstrength/craft-sprout-forms#396]
When submitting a form with reCaptcha enabled, if you inspect the `g-recaptcha-response` field and remove the required attribute you are then able to submit the form without completing the reCaptcha verification. While it appears that the form data is not saved within the forms entries, if a notification email has been setup for the form the form data is still sent to the recipients.

Versions
Craft - 3.3.18.3
Sprout Forms - 3.6.6
Google reCAPTCHA for Sprout Forms - 1.0.6

**Comment by BenParizek** [comment]
Thanks for reporting @javangriff 

I'm in the middle of a busy week here but will dig in when I can.

**Comment by javangriff** [comment]
@BenParizek any update on this? It would be nice to get an ETA of when this will be looked at if possible.

**Comment by BenParizek** [comment]
@javangriff I'm hoping to get to this by this coming week.

**Comment by ademers** [comment]
@javangriff I'm troubleshooting an issue where the form is submitting without completing the reCaptcha. I wonder if related?

Versions
Craft - 3.3.19
Sprout Forms - 3.6.6
Google reCAPTCHA for Sprout Forms - 1.0.6

**Comment by wei2go** [comment]
I had a similar issue before. For some reason after a SproutForms update, the 'Save Data' setting of my forms have been switched off automatically. Since the entry is not saved, the event which the spam protection handlers hook into is not triggered (which I believe was EVENT_BEFORE_SAVE, but now seems to be changed to EVENT_BEFORE_VALIDATE?). So I guess even if your reCaptcha check fails on the front end, the verification process does not even happen on the server side, and then the script will still get through and trigger the handler for sending off notifications. This needs to be fixed, the spam checkers should always be triggered no matter the form is configured to 'Save Data' or not, and if the submission does not pass the spam checker, the rest of the script should not be executed and an error should be fired back immediately.

I fixed the issue by turning on the 'Save Data' option for each form again. But hopefully this issue can be addressed by the Sprout team soon. @BenParizek

**Comment by rauwebieten** [comment]
I have the same problem. Is there a fix?
Our client recieves all notifications with spam data.

**Comment by BenParizek** [comment]
Hi All, I think there are a few things going on in this thread.

1. **Notification Emails triggered for spam entries.** 

I just released Sprout Forms v3.6.9 which updates the 'When a Form Entry is saved' Event to make sure no captcha errors exist before validating and sending an email. @javangriff @rauwebieten 

2. **Form is submitting without filling out captcha.**

@ademers I'm not sure if this is the same issue or not. Please test this update and open a new ticket if your specific problem persists. I'm working on another release for this week that will be addressing the open reCAPTCHA tickets specifically (https://github.com/barrelstrength/craft-sprout-forms/issues/332, https://github.com/barrelstrength/craft-sprout-forms-google-recaptcha/issues/3, https://github.com/barrelstrength/craft-sprout-forms-google-recaptcha/issues/1, https://github.com/barrelstrength/craft-sprout-forms-google-recaptcha/pull/7)

3. **Save Data setting accidentally disabled**

@wei2go Late last year there was a separate `saveData` setting migration bug that should be corrected in the latest releases. This condition existed for a week or two before it was discovered and should have only affected people who updated during that window. If you updated more recently and still saw this issue, please let me know and I'll open another ticket to look into it. Unfortunately, due to the nature of the bug, we could not programmatically fix it as we'd be making assumptions about which installs had the setting disabled from the migration and which had the setting manually disabled by an admin.

For anybody that is not seeing entries saved in the database, please visit the Form settings area and confirm that the 'Save Data' setting is configured as you need.

4. **Expected Captcha Validation Workflow** 

@wei2go The Notification Event logic did move from `EVENT_BEFORE_SAVE` to `EVENT_BEFORE_VALIDATE` however I believe the workflow is working as expected right now. With the new `Spam` status updates we added recently, we chose to treat captcha errors differently than field validation errors.

Separating the captcha and field errors allows us to give you more control over how to route users if they trigger a captcha. Any form submission, even a spam one, that triggers field validation errors will be returned to the form and display those errors. If a spam entry eventually figures out how to submit the form without field errors, when we discover captcha errors we'll respect whatever settings you've chosen in how to handle those. That could mean saving them to the database or not, or routing the user to the thank you page or back to the form. You can update the behavior of this workflow via the `Spam Redirect Behavior` setting in global Spam Protection settings.

Email Notifications are handled outside of the form workflow and get triggered when the `Entry::EVENT_AFTER_SAVE` is triggered (or simulated if you are not saving to the database). This update changes the validation behavior of the 'On Save Form Entry' Notification Event to not trigger when items get flagged as spam.

**Comment by wei2go** [comment]
> Hi All, I think there are a few things going on in this thread.
> 
> 1. **Notification Emails triggered for spam entries.**
> 
> I just released Sprout Forms v3.6.9 which updates the 'When a Form Entry is saved' Event to make sure no captcha errors exist before validating and sending an email. @javangriff @rauwebieten
> 
> 1. **Form is submitting without filling out captcha.**
> 
> @ademers I'm not sure if this is the same issue or not. Please test this update and open a new ticket if your specific problem persists. I'm working on another release for this week that will be addressing the open reCAPTCHA tickets specifically (#332, [barrelstrength/craft-sprout-forms-google-recaptcha#3](https://github.com/barrelstrength/craft-sprout-forms-google-recaptcha/issues/3), [barrelstrength/craft-sprout-forms-google-recaptcha#1](https://github.com/barrelstrength/craft-sprout-forms-google-recaptcha/issues/1), [barrelstrength/craft-sprout-forms-google-recaptcha#7](https://github.com/barrelstrength/craft-sprout-forms-google-recaptcha/pull/7))
> 
> 1. **Save Data setting accidentally disabled**
> 
> @wei2go Late last year there was a separate `saveData` setting migration bug that should be corrected in the latest releases. This condition existed for a week or two before it was discovered and should have only affected people who updated during that window. If you updated more recently and still saw this issue, please let me know and I'll open another ticket to look into it. Unfortunately, due to the nature of the bug, we could not programmatically fix it as we'd be making assumptions about which installs had the setting disabled from the migration and which had the setting manually disabled by an admin.
> 
> For anybody that is not seeing entries saved in the database, please visit the Form settings area and confirm that the 'Save Data' setting is configured as you need.
> 
> 1. **Expected Captcha Validation Workflow**
> 
> @wei2go The Notification Event logic did move from `EVENT_BEFORE_SAVE` to `EVENT_BEFORE_VALIDATE` however I believe the workflow is working as expected right now. With the new `Spam` status updates we added recently, we chose to treat captcha errors differently than field validation errors.
> 
> Separating the captcha and field errors allows us to give you more control over how to route users if they trigger a captcha. Any form submission, even a spam one, that triggers field validation errors will be returned to the form and display those errors. If a spam entry eventually figures out how to submit the form without field errors, when we discover captcha errors we'll respect whatever settings you've chosen in how to handle those. That could mean saving them to the database or not, or routing the user to the thank you page or back to the form. You can update the behavior of this workflow via the `Spam Redirect Behavior` setting in global Spam Protection settings.
> 
> Email Notifications are handled outside of the form workflow and get triggered when the `Entry::EVENT_AFTER_SAVE` is triggered (or simulated if you are not saving to the database). This update changes the validation behavior of the 'On Save Form Entry' Notification Event to not trigger when items get flagged as spam.

Thanks @BenParizek for the new update. It sounds pretty good. I'll try that when I got a chance.

Unfortunately I was probably within the window of that saveData setting migration bug late last year. It was a bit eventful, but we figured out how to fix it eventually.
