### ISSUE TITLE
notifications CC and BCC management gone

### ISSUE THREAD

**Issue by rauwebieten** [barrelstrength/craft-sprout-forms#427]
### Description (screenshots, logs, ...)

After updating to latest release version, I see that the CC and BCC options in the notifications are no longer there.

After testing on our migrated project, I see the old notification entries still have CC's and BCC's defined in the DB, and these are also used to send the emails.

### Additional info

- Craft version: "craftcms/cms": "3.4.5"
- PHP version: 7.3.14
- Plugins & versions: "barrelstrength/sprout-forms": "3.8.2"

**Comment by rauwebieten** [comment]
Update:

When using send method "list", the CC and BCC options are not displayed, but there used to send mails.

**Comment by BenParizek** [comment]
Thanks @rauwebieten 

Working on a fix.

**Comment by BenParizek** [comment]
@rauwebieten We just released Sprout Forms v3.8.3 which should solve this issue.

Just to note, the CC and BCC fields will only display for Single Emails. It's intentional that they no longer display for the Email List option as we wouldn't want to trigger the same CC/BCC email for every email in the list. This release also includes a migration to clean up those fields in the database.
