### ISSUE TITLE
Missing Entries After Plugin Update

### ISSUE THREAD

**Issue by jeremyfrank** [barrelstrength/craft-sprout-forms#430]
### Description
We just updated Sprout Forms from 3.3.0 => 3.7.1.1 to fix an issue described in #305. This appeared to fix the problem (no more service unavailable error on the front-end), however there are still a few issues:

* There was indeed a `ServiceUnavailableHttpException` error in our server logs.
* I do not see a record of the submission in the `craft_sproutformscontent_contact` table.
* Also all of our form entries are missing from the admin, even though they are still in the above db table.

![image](https://user-images.githubusercontent.com/283397/75285561-d96a3e00-57e4-11ea-83b4-3ab071123e12.png)

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.29
- Plugins & versions: code snippet from composer.json below:
```
{
  "require": {
    "craftcms/cms": "3.3.20.1",
    "vlucas/phpdotenv": "^2.4.0",
    "craftcms/aws-s3": "1.2.7",
    "topshelfcraft/environment-label": "3.2.0",
    "aelvan/inlin": "v2.1.1",
    "angellco/spoon": "3.4.3",
    "barrelstrength/sprout-fields": "3.4.4",
    "barrelstrength/sprout-forms": "3.7.1.1",
    "verbb/super-table": "2.3.3",
    "whoisjuan/craft-color-mixer": "1.0.7",
    "viget/craft-disqus-notify": "^2.0",
    "viget/craft-video-embed": "^1.2",
    "clubstudioltd/craft-asset-rev": "6.0.2",
    "nystudio107/craft-typogrify": "1.1.18",
    "superbig/craft-vzaddress": "^2.0",
    "craftcms/redactor": "2.4.0",
    "viget/craft-lever": "^2.0",
    "davist11/craft-reroute": "^2.0",
    "viget/craft-gotowebinar": "0.1.0",
    "lewisjenkins/craft-dynamic-fields": "3.0.10",
    "aelvan/mailchimp-subscribe": "^3.0",
    "markhuot/craftql": "1.3.4"
  }
}
```

**Comment by BenParizek** [comment]
@jeremyfrank Can you check the 'Save Data' setting on your forms and make sure it's set to enabled? Those Entries do not display if Sprout Forms is set to not to save the incoming entries to the DB.

**Comment by jeremyfrank** [comment]
Thank you. It's strange, we have almost 1912 entries, but save data is turned off. 

![image](https://user-images.githubusercontent.com/283397/75347980-f3049780-586f-11ea-9866-80e565189850.png)

![image](https://user-images.githubusercontent.com/283397/75348026-0d3e7580-5870-11ea-90bb-a5e6634bbf7a.png)

I've turned it on and will run some more tests.

**Comment by BenParizek** [comment]
@jeremyfrank I believe the disabling of the setting happened in one of the migrations. Re-enabling that should get things working as expected again for you and I'll look into the broader issue.

**Comment by jeremyfrank** [comment]
Re-enabling the "Save Data" toggle fixed the submission saving, and displaying all the old entries in the admin. Thank you! I ran a few tests, and what I'm seeing now is that only my first test displays in the admin, the rest of them do not, but all of them are definitely saved in the db table.

![image](https://user-images.githubusercontent.com/283397/75350025-ca7e9c80-5873-11ea-94e6-e75480dd816e.png)

**Comment by jeremyfrank** [comment]
I found another issue related to file upload fields. It's likely unrelated so I opened a new issue for that one: #433.

**Comment by BenParizek** [comment]
@jeremyfrank I'm unable to recreate this. Do you see any errors in your Craft logs or on the console tab in your Web Browser's developer tools?

**Comment by BenParizek** [comment]
@jeremyfrank I believe I know what the issue might relate to. You mentioned you upgrade to v3.7.1.1 which makes me think your choosing to stay on Craft 3.3.x instead of upgrade to 3.4 right now. We have a bug relating to how we identified the proper dependencies in our composer files for the 3.4 releases. I'll post an update to this thread shortly with more info in how to make sure all the right files are installed.

**Comment by jeremyfrank** [comment]
Yes, for now we are staying on Craft 3.3.x, but we hope to update to 3.4.x as soon as we have time to devote to testing and QA for plugins, due to their changelog note about [behavior changes for plugin developers](https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#340---2020-01-28).

**Comment by jeremyfrank** [comment]
I checked the server's `web.log` file and saw some info for each of the Jane/Jon Doe submissions in that screenshot I added earlier. Looks like something to do with either duplicate entries or captcha errors (or both).

```
2020-02-26 08:37:26 [-][-][-][error][barrelstrength\sproutforms\captchas\DuplicateCaptcha::verifySubmission] Submission appears to be a duplicate.
2020-02-26 08:37:28 [-][-][-][error][barrelstrength\sproutbaseemail\services\NotificationEmailEvents::handleDynamicEvent] When a form entry is saved (Sprout Forms) event does not validate: {"event":["Submitted entry has captcha errors."]}
```

**Comment by BenParizek** [comment]
Sprout Forms depends on a handful of other modules to support all of its features. We define in our composer.json file which of those modules to pull in. There is a bug in that composer configuration if you are trying to stay on Craft 3.3.x. When you update to the latest, some more recent versions of the modules get pulled into the project that assumes you have updated things to Craft 3.4. To resolve this you have two options:

1. Upgrade to Craft 3.4 and any plugins to Craft 3.4 compatible versions. This will trigger the appropriate migrations to get the files and database back in sync.
2. Manually define the Craft 3.3 compatible plugins AND dependencies in your composer.json file

This issue will affect Sprout Forms (and also Sprout Email and Sprout Reports if you have them installed in any other places where you are trying to stay on Craft 3.3 right now).

For option 2, you will want to define the specific dependencies below in your composer.json file:

```
"barrelstrength/sprout-forms": "3.7.1.1",
"barrelstrength/sprout-email": "4.0.7",
"barrelstrength/sprout-reports": "1.2.11",
"barrelstrength/sprout-base": "5.0.9",
"barrelstrength/sprout-base-reports": "1.3.10"
"barrelstrength/sprout-base-fields": "1.2.3"
```

With those in place, you can delete your vendor folder and composer.lock file and re-run `composer update` and that should pull in all the proper dependencies for Sprout Forms to be Craft 3.3 compatible again.

If you do hard code these dependencies in your projects composer.json, whenever you do update to Craft 3.4 make a note to remove all of the `sprout-base*` dependencies and let the plugins handle those dependencies again.

Because of this scenario, I'd like to make sure you have the proper version of all these modules in place before we troubleshoot the Entries bug above. There's a chance the above bug is just a side-effect of the wrong files in place right now.

Let me know if you have any follow up questions. I know this gets into some more technical territory with managing composer dependencies.

**Comment by jeremyfrank** [comment]
Thanks Ben for the detailed writeup. It makes sense that the sprout-forms sub-dependancies might not be in-sync with our particular 3.3 version of Craft. I chatted with the team here and we're going to put some time in this week on option 1, just updating Craft to the latest 3.4 and all plugins. I'll follow up after that's wrapped up to let you know how it went and if there are any lingering issues.

**Comment by jeremyfrank** [comment]
Closing the loop on this. I got Craft and all the plugins updated and we QAd and verified everything working on our staging environment. We did uncover one migration issue with another third party plugin, and I logged that here (https://github.com/angell-co/Spoon/issues/91). Thanks for your help with all of this!
