### ISSUE TITLE
Validation Warning - no heading (SOLUTION INCLUDED)

### ISSUE THREAD

**Issue by 919Studios** [barrelstrength/craft-sprout-forms#444]
### Description (screenshots, logs, ...)
During html validation, a warning will occur as: 
"vendor/barrelstrength/sprout-forms/src/templates/_components/formtemplates/accessible/tab.twig" does not contain a heading element after the `<section class="tab">`

### Steps to reproduce

1. **Create a form and use HTML validator on the page (https://validator.w3.org/#validate_by_input).**
2. **You'll notice you get a warning stating: *"you have a section with no heading element"***.

### SOLUTION I USED TO SOLVE THIS WARNING:
Below the `<section class="tab">` I'm using the following HTML: 

````HTML
<h2 class="visuallyHidden">clear out sprouts warnings on validation</h2>
````
And in my CSS, I'm using this code to visually remove the heading:

````CSS
.visuallyHidden {
	display: none;
}
````

**This will solve the warning and result in 100% validation with no warnings or errors from Sprout Forms.**

- Craft version: **Craft Pro-3.3.20.1**
- PHP version: **7.1.6**
- Plugins & versions: **Sprout Forms-3.7.1.1**

**Comment by BenParizek** [comment]
Thanks @919Studios 

I'll review and see if we can address this in our default templates.

**Comment by BenParizek** [comment]
@919Studios I've taken a closer look at this.

First, while I do want to support proper markup wherever possible there may be some areas where there are tradeoffs to support various settings. In this case, we do have a setting to enable headings on each tab. Under the Form->Settings->Templates you will find a "Page Titles" setting. Enabling that setting will output an `<h3>` page heading for each tab. You could choose to hide that if you prefer to have all the warnings fixed in the HTML. By default, we don't display those headings as we've found that's works best for the majority of simple use cases.

Alternatively, we have a very flexible Form Template override API and you can override any of the default templates to behave more in line with what you prefer. I expect there may be a few other scenarios where we might have validation warnings.

I can keep these considerations in mind as we update our base forms over time. I expect the route I'd consider addressing this with in our base templates would be to swap out that `<section>` wrapper with a more generic `<div>` to be a bit more flexible for the various formats that may get output in the form HTML when different settings are selected.

I'm going to update this to a feature request and will revisit in the next major release or bigger template restructuring we work on.

**Comment by 919Studios** [comment]
@BenParizek, your recomendation worked perfectly!  Once I turned on Page Titles the `<h3>` took care of html validation warning I was getting.  Thank you for the tip!
