### ISSUE TITLE
Issue with Date/time field in forms - submitted form not attached in email

### ISSUE THREAD

**Issue by AnnaZLinka** [barrelstrength/craft-sprout-forms#459]
### Hei 
We have used **Date/Time** field in one of our forms with default configuration. Have noticed that sending of the form after submit is registered in craft entries, email with notification is send, but no form is attached to it (even if the notification specifies Templates: Basic Notification (Sprout Forms)). When testing on production env to show the form (with the little eye icon) I constantly get Internal Server Error. On local env it shows "strip_tags() expects parameter 1 to be string, object given", while in logs stays that it get's array when expecting string.

### Steps to reproduce

1. Use Date/Time field in a form.
2. Connect form to a notification. n notification choose Templates: Basic Notification (Sprout Forms).
3. Connect to a site on front. 
4. Fill the form and submit.
5. In admin panel in notifications check the notifications with "eye" preview. 

### Additional info

- Craft version: Craft Pro 3.4.15
- PHP version: 7.2.24
- Database driver & version:  MySQL 5.7.29
- Plugins & versions: 3.9.0.1

**Comment by BenParizek** [comment]
Thanks for the detailed report @AnnaZLinka 

I think the issue here is that we overlooked adding support for the DateField to the base email template. I'll get that in the queue to fix. In the meantime, if you need to get this working you can select "Custom" as your email template and set a custom folder in your templates folder to use for the email template. Copy our base email template to your Custom Email Template folder as `email.twig`

Here's the base template we use:
https://github.com/barrelstrength/craft-sprout-forms/blob/v3.9.0.1/src/templates/_integrations/sproutemail/emailtemplates/basic/email.twig

I believe the fix will be to add another conditional to address the date field syntax. Something like (untested):

``` twig
{% elseif field.getFieldInputFolder() == 'date' %}

    {{ value|date('Y-m-d') }}
    <br>
```

**Comment by AnnaZLinka** [comment]
No worries @BenParizek :)

Thanks for the solution proposition. We've managed with using just a simple field there for now - date format wasn't so important after all in our case. Although looking forward for a fix.

**Comment by BenParizek** [comment]
@AnnaZLinka We just released Sprout Forms vv3.11.3. The date field should now display in Email Notifications. Thanks for reporting.
