### ISSUE TITLE
When saving a new field Rule, the Condition disappears.

### ISSUE THREAD

**Issue by franciurachel** [barrelstrength/craft-sprout-forms#473]
I am having a double issue and cannot make the field Rules work.
First of all, they don't get saved in the backend. So, after I save a field rule with some conditions when I go back to the field Rule, values and conditions are empty, yet in the template, they appear (data-rules attr).
In the front-end, I get the error below from rules.js. And nothing work.

1. Create a new field Rule (for instance Second Name is Some Value)
2. Save it
3. Open the field Rule and the Value has disappeared (and the field of the Conditions rolls back to the first one of the dropdown)
4. In your template data-rules attribute in <form> is correct
5. Disabled attribute assigned to the condition target element but no classes
6. It does not work 

Error: _'Cannot create property 'disabled' on number '1'_

- Craft version: 3.4.19
- PHP version: 7.3
- Plugins & versions: 3.11

<img width="908" alt="Screen Shot 2020-05-12 at 18 23 10" src="https://user-images.githubusercontent.com/6681670/81720152-4b663100-947e-11ea-893c-84b8a192c93a.png">

**Comment by BenParizek** [comment]
Thanks for the detailed report @franciurachel. I'm catching up on a few tickets and will review this as soon as I can.

**Comment by gdelorey** [comment]
We're experiencing the same issue. Subscribing :)

**Comment by BenParizek** [comment]
@franciurachel @gdelorey This should be resolved in release v3.11.6.

I've also added some additional cleanup so that if you happen to delete a field that is being used in an existing Rule, Sprout Forms will also remove that particular conditional statement that will no longer validate or delete the entire rule if that field was the only condition or behavior target of the rule.

Let me know if you run into anything else.

**Comment by franciurachel** [comment]
Thanks Ben
