### ISSUE TITLE
Unable to save Show Reports Tab

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-forms#475]
### Description (screenshots, logs, ...)
I can't save the state of the "Show Reports Tab". I do not have Sprout Report installed. See video https://d.pr/free/v/aKbS8G 

### Additional info

- Craft version: 3.4.19
- Sprout Forms: 3.11.3

**Comment by BenParizek** [comment]
I can recreate this. Looking into a solution.

**Comment by BenParizek** [comment]
@engram-design I believe this is just a display bug. Currently, that setting can only be used if Sprout Reports is installed. There is a warning that should display but it looks like the issue here is that message isn't displaying and making that known. I'll fix that in the next release:
https://github.com/barrelstrength/craft-sprout-forms/commit/c168640b27b84f08fa1baf5f2a3c6efab241c8f0

Do you have a use case where you want to hide the Reporting feature in general?

**Comment by engram-design** [comment]
Just wanted to clean up the sidebar sub-nav items, similar to removing Notifications, because its confusing.

Its not exactly earth-shattering that I can't hide the tab, just thought to let you know.

**Comment by BenParizek** [comment]
@engram-design The warning message for this should show up again in the latest release.

I'll consider adding additional controls to display/hide those tabs but I'd prefer to explore making them feel more useful out the gates to begin with first. Do you have any feedback on how those pages could be improved so that you'd be less inclined to want to hide them out of the box?

Would better defaults for Reports and Notifications that don't need any configuration help?
