### ISSUE TITLE
Spam protection settings tab error after update to 3.12

### ISSUE THREAD

**Issue by lexislav** [barrelstrength/craft-sprout-forms#491]
**Twig Runtime error
Impossible to access a key ("honeypotFieldName") on a null variable.**

when trying access the spam protection tab in sprout form settings.
![image](https://user-images.githubusercontent.com/7147349/82873861-726c3a80-9f35-11ea-86c4-1129d81131ac.png)

**Comment by BenParizek** [comment]
@lexislav Could you share what version of Sprout Forms you were upgrading from when you ran into this?

One potential workaround that may be able to get things running again for you while we look into it would be to add those settings to the Sprout Forms config override file `config/sprout-forms.php`

https://github.com/barrelstrength/craft-sprout-forms/blob/v3.12.2/src/config.php#L86

**Comment by BenParizek** [comment]
Also note, the format of those settings recently changed:
https://sprout.barrelstrengthdesign.com/docs/forms/installing-and-updating-craft-3.html#upgrading-to-forms-v3-10-0

**Comment by lexislav** [comment]
I keep the line with updates, not miss a single one…

The override file setting worked for me.

Whats is correct settings format for google-recaptcha? Like this?

'barrelstrength\sproutforms\captchas\GoogleRecaptcha'  => [

Thanks

**Comment by BenParizek** [comment]
@lexislav Each plugin has an example `src/config.php` with the settings. You can see the reCAPTCHA format here, however it looks like we need to update that with the new format that you have mentioned so `sproutformsgooglerecaptcha-googlerecaptcha` should be `barrelstrength\sproutforms\captchas\GoogleRecaptcha`: https://github.com/barrelstrength/craft-sprout-forms-google-recaptcha/blob/v1/src/config.php

**Comment by BenParizek** [comment]
I'm unable to recreate this in various tests so I'm probably missing a detail somewhere. If the override workaround works for now, please roll with that. We're in the middle of refactoring our settings architecture to improve on a few scenarios where settings have become tricky to manage and will be reviewing all these settings and how they are stored as we do that. 

If this issue comes up for anyone else, I'll need more info to help track down what's going on such as if you are using the config overrides before the update, what the settings appeared to be before and after the update, etc.

**Comment by lexislav** [comment]
The override workaround works just now. Don’t worry…

**Comment by BenParizek** [comment]
As of the Sprout Forms v3.13.4 release, this should now be addressed properly in the migrations.
