### ISSUE TITLE
Custom notification field no longer displaying correct form values

### ISSUE THREAD

**Issue by Christopholus** [barrelstrength/craft-sprout-forms#501]
### Description (screenshots, logs, ...)
Since updating to a recent version of Sprout forms, all form notifications are being sent with  variable names instead of their values from the form.

We're using a custom field to render the content of our notifications a field called "emailBody". We use a custom notification template, where we render this field with {{emailBody}}.

However, all fields such as "{firstName}" or "{email}" are now just displaying their variable names, instead of rendering the actual form values.

**Notification Example:**
![notification_example](https://user-images.githubusercontent.com/1195612/84281166-3ecd0b00-ab06-11ea-8535-cd94dc9e8ee0.jpg)

**The email that we now receive:**
![email_example](https://user-images.githubusercontent.com/1195612/84281184-442a5580-ab06-11ea-96a3-0d949e373958.jpg)

This was working as intended until just updating previously. Not sure what might have changed, please let us know if we need to render our email templates with a |raw tag or similar.

Thanks!

### Steps to reproduce

1. Create notification with custom field.
2. Enter in any variables to be rendered from the form.
3. Send notification email, and see variable names instead of form values

### Additional info

- Craft version:  3.4.22.1
- PHP version: 7.1.33
- Database driver & version:  MySQL 5.5.5
- Plugins & versions: 3.12.2

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by riusi88** [comment]
I'm experiencing this same issue as well. Had to revert all notifications to use the default templates for the time being to get them working with the variable names. 

- Craft:  3.4.22.1
- Sprout Email : 4.4.7
- Sprout Fields: 3.8.3
- Sprout Forms: 3.12.2

**Comment by Christopholus** [comment]
Thanks @riusi88 , I ended up rolling my templates back to the default form templates for now to keep our client's notifications at least working correctly for now. @BenParizek please let me know if I can provide any more detail to help aid in the fix

**Comment by BenParizek** [comment]
Thanks for reporting. I will update this thread when I have more info.

**Comment by BenParizek** [comment]
@Christopholus @riusi88

This is the expected behavior now. This feature was changed due to a security vulnerability and is mentioned in the [upgrade notes](https://sprout.barrelstrengthdesign.com/docs/email/installing-and-updating-craft-3.html#upgrading-to-email-v4-2-0).

To create similar behavior you will need to do what it sounds like you'v done – confine your dynamic variables in the Control Panel to the Subject or Default Body fields. Any other custom variables will need to be added and managed in a [custom email template](https://sprout.barrelstrengthdesign.com/docs/email/template-overrides.html).

When I have a chance, I will consider adding back improved functionality in the CP workflow if we can find a way to do it safely. I'll update [this ticket](https://github.com/barrelstrength/craft-sprout-email/issues/174) when I can say more.
