### ISSUE TITLE
Duplication / Saving and then deleting the copy causes error "Invalid field layout ID: "

### ISSUE THREAD

**Issue by heggemsnes** [barrelstrength/craft-sprout-forms#568]
### Description (screenshots, logs, ...)

Deleting a copied form causes internal server error.

In DB two elements with same ID shows up. Deleting both removes the error ( but also the forms ).

### Steps to reproduce

1. Create a form with some fields
2. Save it as a new form
3. Save the new form
4. Delete the copy
5. Error page shows up

### Additional info

- Craft version: Craft Pro 3.6.11.2
- PHP version: 7.4.15
- Database driver & version:  MySQL 5.7.32
- Plugins & versions: Sprout Forms	3.13.4

**Comment by BenParizek** [comment]
@heggemsnes I can recreate this issue. Looking into a fix.

**Comment by BenParizek** [comment]
@heggemsnes It appears that we were not properly updating the duplicated form with the new field layout ID. So a new field layout exists in the database, but the duplicated form gets created with a duplicate field layout ID from the form it was duplicating. Once one of the forms is deleted, the other will no longer have a matching field layout in the database and trigger the error you describe.

I've just released Sprout Forms v3.13.5 that fixes the bug, so new forms that are duplicated should behave as expected now.

Unfortunately, I cannot write a migration to fix the issue because I would need to make an assumption about which of the two forms in the database has the duplicate layout (used by both the original form and the duplicate form) and it's possible that you are using the original or duplicate form on your site as the form you expect to be using the shared field layout.

To fix the issue, you will need to manually reassign the orphaned field layout to the form that you want to have using it. I'll describe this below, and if you're not comfortable working directly with the database please reach out to sprout@barrelstrengthdesign.com and we can walk through this on a screenshare.

## Fixing orphaned Field Layouts on duplicated Form Elements

Look at `craft_sproutforms_forms` table and see if you have any duplicate `fieldLayoutId`s:

| id | fieldLayoutId | name |
|:-- |:-- |:-- |
| 84 | 41 | Form 1 |
| 85 | 41 | Form 2 |
| 86 | 43 | Form 3 |

Here, you see that we have two forms (Element IDs: `84` and `85`) using the same field layout ID (`41`)

Next, we need to go to the `craft_fieldlayouts` table and look for all the field layouts from `fieldLayoutId` `41` up until the next form that exists (if another exists). We are looking for an orphaned field layout that was created when we duplicated our form but that was never mapped to the new form.

In this case, we can see in our `craft_fieldlayouts` table that `fieldLayoutId` `41`, `42`, and `43` exist.

| id | type |
|:-- |:-- |
| 41 | barrelstrength\sproutforms\elements\Form |
| 42 | barrelstrength\sproutforms\elements\Form |
| 43 | barrelstrength\sproutforms\elements\Form |

As we only see layouts `41` and `43` in our `craft_sproutforms_forms` table, we can conclude that the form `fieldLayoutId` `42` currently does not have a match, and we can confirm that by making sure we don't see that orphaned `fieldLayoutId` `42` in the `craft_sproutforms_forms.fieldLayoutId` column.

Now that we have identified `fieldLayoutId` `42` as our orphaned layout, we can update the `craft_sproutforms_forms` table and change the second, duplicate instance of `craft_sproutforms_forms.fieldLayoutId` from the duplicate `fieldLayoutId` `41` to the orphaned `fieldLayoutId` `42`.

If, based on how you are using the forms you prefer the duplicate form to keep the current layout, you can update the original form with the orphaned `fieldLayoutId`.
